/**
 * The causes a symptom can be narrowed to. Each explains what the part is,
 * what it feels like when it is the culprit, an indicative cost of having it
 * done, and where it sits in the job catalogue. Costs are UK ranges for
 * planning, never quotes; no torque, capacity or part-number figures appear.
 */
import type { CauseDefinition } from "./types";

const CAUSE_LIST: CauseDefinition[] = [
  // ---- Braking ----
  {
    id: "worn-brake-pads",
    name: "Worn brake pads",
    what: "The friction blocks that squeeze the disc. They wear down every time you brake.",
    fits: "A grinding or scraping noise that changes when you press the pedal, often worse at low speed.",
    costGbp: { min: 90, max: 180 },
    jobId: "front-brake-pads",
    tier: "amber",
    motRuleIds: ["brakes.pads_thin"],
    ownCheck: "Look through the wheel spokes at the edge of the disc. If the friction material on the pad looks thinner than the metal backing plate, they are due.",
  },
  {
    id: "worn-brake-discs",
    name: "Worn or scored brake discs",
    what: "The metal plates the pads grip. They wear, and they warp if they get very hot.",
    fits: "A deep grinding or a rhythmic pulsing through the pedal, sometimes with a lip you can feel at the disc edge.",
    costGbp: { min: 160, max: 350 },
    jobId: "front-brake-discs-and-pads",
    tier: "amber",
    motRuleIds: ["brakes.disc_worn"],
    ownCheck: "Run a fingernail across the disc face. Deep grooves you can catch a nail in, or a pronounced lip at the outer edge, mean it is worn.",
  },
  {
    id: "warped-discs",
    name: "Distorted brake discs",
    what: "A disc that is no longer perfectly flat, usually from heat.",
    fits: "The pedal pulses under your foot and the steering wheel shakes, only while braking, and worse from higher speeds.",
    costGbp: { min: 160, max: 350 },
    jobId: "front-brake-discs-and-pads",
    tier: "amber",
    ownCheck: "If the shake appears only when you brake and disappears when you release, it is the brakes rather than the wheels.",
  },
  {
    id: "sticking-caliper",
    name: "Sticking brake caliper",
    what: "The caliper should release cleanly. Seized slider pins or a stuck piston keep the pad pressed on the disc.",
    fits: "The car pulls to one side, one wheel is much hotter than the other after a drive, and that corner's pads wear out fast.",
    costGbp: { min: 120, max: 300 },
    jobId: "front-brake-pads",
    tier: "amber",
    motRuleIds: ["brakes.uneven"],
    ownCheck: "After a short drive, carefully hold your hand near each front wheel. One much hotter than the other points at a sticking caliper.",
  },
  {
    id: "brake-fluid-leak",
    name: "Brake fluid leak or air in the system",
    what: "The hydraulic system that carries your foot's push to the brakes.",
    fits: "A pedal that feels soft, sinks slowly under steady pressure, or goes further than it used to.",
    costGbp: { min: 100, max: 300 },
    jobId: "brake-pipe-or-hose",
    tier: "amber",
    motRuleIds: ["brakes.pipe_hose"],
    ownCheck: "Check the brake fluid reservoir level and look for wet patches on the inside of the wheels and under the car.",
  },
  {
    id: "abs-fault",
    name: "ABS fault",
    what: "The anti-lock system, usually a wheel-speed sensor or its wiring.",
    fits: "The ABS light is on. Normal braking still works but the anti-skid function may not.",
    costGbp: { min: 80, max: 250 },
    jobId: "read-fault-codes",
    tier: "green",
    motRuleIds: ["brakes.abs_lamp"],
    ownCheck: "Read the fault codes with a cheap OBD reader: it usually names which wheel's sensor is unhappy.",
  },

  // ---- Handling and steering ----
  {
    id: "wheel-balance",
    name: "Wheels out of balance",
    what: "Small weights on the rim keep the wheel spinning smoothly. They fall off.",
    fits: "A steady vibration that appears around a particular speed and is there whether you brake or not.",
    costGbp: { min: 30, max: 60 },
    tier: "green",
    ownCheck: "If the shake comes in at one speed band and fades above and below it, balancing is the first thing to try. Any tyre shop does it while you wait.",
  },
  {
    id: "worn-tyres",
    name: "Worn or damaged tyres",
    what: "The only part of the car touching the road.",
    fits: "Uneven wear across the tread, a bulge in the sidewall, or a vibration that changes with speed.",
    costGbp: { min: 60, max: 200 },
    tier: "green",
    motRuleIds: ["tyres.near_limit", "tyres.damage"],
    ownCheck: "Check the tread depth across the whole width of each tyre and look for bulges. Uneven wear across one edge points at alignment.",
  },
  {
    id: "wheel-alignment",
    name: "Wheel alignment out",
    what: "The angles the wheels sit at relative to the road and each other.",
    fits: "The car pulls to one side on a flat road, or the steering wheel is off-centre when going straight.",
    costGbp: { min: 40, max: 90 },
    tier: "green",
    ownCheck: "Look at the inner and outer edges of the front tyres. Wear on one edge only is the classic alignment signature.",
  },
  {
    id: "worn-suspension-joint",
    name: "Worn suspension joint or bush",
    what: "The pivots the suspension arms move on. They wear and develop play.",
    fits: "Knocking over bumps, vague steering, and uneven tyre wear.",
    costGbp: { min: 120, max: 350 },
    jobId: "suspension-arm-ball-joint",
    tier: "amber",
    motRuleIds: ["suspension.joint", "suspension.arb"],
    ownCheck: "With the car safely on stands, rock each wheel top-to-bottom and side-to-side. Any knocking or play is a worn joint.",
  },
  {
    id: "worn-shock-absorber",
    name: "Worn shock absorbers",
    what: "The dampers that stop the car bouncing after a bump.",
    fits: "The car floats or wallows, keeps bouncing after a bump, and dives hard under braking.",
    costGbp: { min: 150, max: 400 },
    jobId: "shock-absorbers",
    tier: "amber",
    motRuleIds: ["suspension.shock"],
    ownCheck: "Push down hard on one corner and let go. It should settle in one movement; two or three bounces means the damper is tired.",
  },
  {
    id: "worn-wheel-bearing",
    name: "Worn wheel bearing",
    what: "The bearing the wheel spins on.",
    fits: "A hum or drone that rises with speed and changes as you swerve gently left and right.",
    costGbp: { min: 130, max: 350 },
    jobId: "wheel-bearing",
    tier: "amber",
    motRuleIds: ["wheels.bearing"],
    ownCheck: "On a quiet road, gently weave. If the noise gets louder turning one way and quieter the other, it is a bearing on the loaded side.",
  },
  {
    id: "steering-joint-wear",
    name: "Worn steering joint",
    what: "The track rod ends and rack joints that connect the steering to the wheels.",
    fits: "Play at the steering wheel before the car responds, and knocking over small bumps.",
    costGbp: { min: 90, max: 220 },
    jobId: "track-rod-end",
    tier: "amber",
    motRuleIds: ["steering.joint", "steering.play"],
  },

  // ---- Starting ----
  {
    id: "flat-battery",
    name: "Flat or failing battery",
    what: "The battery that turns the starter motor.",
    fits: "A rapid clicking, dash lights dimming as you turn the key, or nothing at all. Often worse on cold mornings.",
    costGbp: { min: 80, max: 200 },
    jobId: "battery-replacement",
    tier: "green",
    motRuleIds: ["lamps.battery"],
    ownCheck: "Turn the headlights on without starting. If they are dim, or dim a lot when you turn the key, suspect the battery.",
  },
  {
    id: "bad-battery-connection",
    name: "Loose or corroded battery terminals",
    what: "The clamps carrying every amp the starter needs.",
    fits: "Intermittent no-starts, sometimes fixed by wiggling a terminal, with white or green fur on the posts.",
    costGbp: { min: 0, max: 40 },
    jobId: "battery-replacement",
    tier: "green",
    ownCheck: "With the engine off, try to twist each terminal clamp by hand. It should not move at all.",
  },
  {
    id: "failing-alternator",
    name: "Failing alternator",
    what: "The generator that charges the battery while the engine runs.",
    fits: "A battery warning light while driving, lights that dim at idle, and a battery that goes flat again after a jump start.",
    costGbp: { min: 200, max: 500 },
    jobId: "alternator",
    tier: "amber",
    ownCheck: "If a jump start works but the car dies soon after, or the battery light is on while driving, the alternator is the suspect.",
  },
  {
    id: "starter-motor",
    name: "Starter motor",
    what: "The motor that spins the engine to start it.",
    fits: "A single loud click with strong dash lights, or a whirring without the engine turning.",
    costGbp: { min: 180, max: 450 },
    tier: "amber",
  },
  {
    id: "fuel-delivery",
    name: "Fuel delivery problem",
    what: "The pump and filter that get fuel to the engine.",
    fits: "The engine turns over normally but will not fire, sometimes after a whining from the back of the car.",
    costGbp: { min: 150, max: 500 },
    tier: "red",
  },
  {
    id: "immobiliser",
    name: "Immobiliser or key fault",
    what: "The security system that will not let the engine run without the right key.",
    fits: "The engine turns over but never fires, often with a key or padlock symbol lit on the dash.",
    costGbp: { min: 60, max: 250 },
    tier: "green",
    ownCheck: "Try the spare key. If the car starts, it is the first key or its battery.",
  },

  // ---- Running ----
  {
    id: "misfire-ignition",
    name: "Misfire: plugs or coils",
    what: "One cylinder is not firing properly, usually a worn spark plug or a failing ignition coil.",
    fits: "The engine shakes at idle, feels flat under acceleration, and the engine light often flashes or comes on.",
    costGbp: { min: 60, max: 300 },
    jobId: "spark-plugs",
    tier: "green",
    ownCheck: "Read the fault codes: a misfire code names the cylinder, which turns a guess into a job.",
  },
  {
    id: "air-leak",
    name: "Air leak into the intake",
    what: "A split hose or perished seal letting unmeasured air into the engine.",
    fits: "A rough or hunting idle, sometimes a hissing or whistling under the bonnet.",
    costGbp: { min: 60, max: 250 },
    tier: "amber",
  },
  {
    id: "dirty-air-filter",
    name: "Clogged air filter",
    what: "The paper element that keeps dirt out of the engine.",
    fits: "Gradual loss of power and worse economy, on a car that has done a lot of miles since its last service.",
    costGbp: { min: 10, max: 40 },
    jobId: "engine-air-filter",
    tier: "green",
    ownCheck: "Open the air box and hold the element up to the light. If you cannot see light through it, it is done.",
  },
  {
    id: "dpf-blocked",
    name: "Blocked diesel particulate filter",
    what: "The filter that traps soot in a diesel exhaust. It needs long, hot runs to clear itself.",
    fits: "A warning light, reduced power, and a car used mostly for short cold journeys.",
    costGbp: { min: 250, max: 1200 },
    jobId: "emissions-diagnosis",
    tier: "red",
    motRuleIds: ["nuisance.emissions"],
    ownCheck: "A steady half-hour run at motorway speed, if the light and the handbook allow it, is what the system needs to regenerate.",
  },
  {
    id: "overheating-cooling",
    name: "Cooling system fault",
    what: "The coolant, thermostat, pump and fans that keep the engine at temperature.",
    fits: "The temperature gauge climbs, especially in traffic, and there may be a sweet smell or steam.",
    costGbp: { min: 100, max: 600 },
    jobId: "coolant-drain-and-refill",
    tier: "amber",
    motRuleIds: ["nuisance.fluid_leak"],
    ownCheck: "With the engine stone cold, check the coolant level in the expansion tank. Low means a leak somewhere.",
  },
  {
    id: "clutch-wear",
    name: "Worn clutch",
    what: "The friction plate that connects the engine to the gearbox.",
    fits: "The engine revs climb without the car accelerating, especially in a high gear uphill, and there may be a burning smell.",
    costGbp: { min: 400, max: 1000 },
    tier: "red",
  },

  // ---- Noises ----
  {
    id: "worn-aux-belt",
    name: "Worn auxiliary belt or tensioner",
    what: "The belt that drives the alternator and other accessories.",
    fits: "A squeal on start-up or when you turn the wheel, often worse when cold or damp.",
    costGbp: { min: 80, max: 250 },
    jobId: "auxiliary-drive-belt",
    tier: "amber",
    motRuleIds: ["nuisance.noise"],
  },
  {
    id: "exhaust-leak",
    name: "Exhaust leak",
    what: "A hole or a failed joint in the exhaust.",
    fits: "A blowing or droning that rises with the engine, louder under acceleration.",
    costGbp: { min: 60, max: 300 },
    jobId: "exhaust-section",
    tier: "amber",
    motRuleIds: ["body.exhaust"],
  },
  {
    id: "loose-heat-shield",
    name: "Loose heat shield",
    what: "A thin metal shield over the exhaust. Its mountings rust away.",
    fits: "A tinny rattle at a particular engine speed that stops when you touch the throttle.",
    costGbp: { min: 20, max: 80 },
    tier: "green",
    ownCheck: "With the exhaust cold, reach under and try to move the shields by hand. A rattly one moves easily.",
  },

  // ---- Leaks and smells ----
  {
    id: "engine-oil-leak",
    name: "Engine oil leak",
    what: "Oil escaping from a seal or gasket.",
    fits: "Dark brown or black drips under the middle of the car and a falling oil level.",
    costGbp: { min: 80, max: 600 },
    jobId: "top-up-fluids",
    tier: "green",
    motRuleIds: ["nuisance.oil_leak"],
    ownCheck: "Put cardboard under the car overnight. The colour and position of the drip narrow it down: black is engine oil, pink or green is coolant, clear and thin is usually air-con condensation and harmless.",
  },
  {
    id: "coolant-leak",
    name: "Coolant leak",
    what: "Coolant escaping from a hose, the radiator or the pump.",
    fits: "Pink, green or orange drips, a sweet smell, and a coolant level that keeps falling.",
    costGbp: { min: 80, max: 500 },
    jobId: "coolant-drain-and-refill",
    tier: "amber",
    motRuleIds: ["nuisance.fluid_leak"],
  },
  {
    id: "fuel-leak",
    name: "Fuel leak",
    what: "Petrol or diesel escaping.",
    fits: "A strong fuel smell and a wet patch that evaporates.",
    costGbp: { min: 100, max: 500 },
    jobId: "fuel-injectors-rail",
    tier: "red",
    motRuleIds: ["body.fuel_leak"],
  },
  {
    id: "burning-smell-brakes",
    name: "Overheating brakes",
    what: "A brake that is dragging and getting very hot.",
    fits: "A sharp, acrid burning smell after a drive, worst at one wheel.",
    costGbp: { min: 120, max: 300 },
    jobId: "front-brake-pads",
    tier: "amber",
  },
];

export const CAUSES: Record<string, CauseDefinition> = Object.fromEntries(CAUSE_LIST.map((c) => [c.id, c]));

export function getCause(id: string): CauseDefinition | null {
  return CAUSES[id] ?? null;
}
