/**
 * Generic OBD-II code descriptions from the SAE J2012 standard, which is a
 * public standard for the P0xxx / C0xxx / B0xxx / U0xxx ranges. Bundled as
 * static data: no API, no lookups, no cost.
 *
 * This is the common subset a home mechanic actually meets, not the whole
 * standard. A code that is not here is decoded structurally and the user is
 * told plainly that we do not have its exact description.
 */
export const GENERIC_CODES: Record<string, string> = {
  // --- Fuel and air metering ---
  P0100: "Mass or volume air flow circuit",
  P0101: "Mass or volume air flow circuit range/performance",
  P0102: "Mass or volume air flow circuit low input",
  P0103: "Mass or volume air flow circuit high input",
  P0106: "Manifold absolute pressure/barometric pressure circuit range/performance",
  P0107: "Manifold absolute pressure/barometric pressure circuit low input",
  P0108: "Manifold absolute pressure/barometric pressure circuit high input",
  P0110: "Intake air temperature sensor circuit",
  P0112: "Intake air temperature sensor circuit low input",
  P0113: "Intake air temperature sensor circuit high input",
  P0115: "Engine coolant temperature circuit",
  P0116: "Engine coolant temperature circuit range/performance",
  P0117: "Engine coolant temperature circuit low input",
  P0118: "Engine coolant temperature circuit high input",
  P0120: "Throttle/pedal position sensor/switch A circuit",
  P0121: "Throttle/pedal position sensor/switch A circuit range/performance",
  P0122: "Throttle/pedal position sensor/switch A circuit low input",
  P0123: "Throttle/pedal position sensor/switch A circuit high input",
  P0128: "Coolant thermostat: coolant temperature below thermostat regulating temperature",
  P0130: "O2 sensor circuit (bank 1, sensor 1)",
  P0131: "O2 sensor circuit low voltage (bank 1, sensor 1)",
  P0132: "O2 sensor circuit high voltage (bank 1, sensor 1)",
  P0133: "O2 sensor circuit slow response (bank 1, sensor 1)",
  P0134: "O2 sensor circuit no activity detected (bank 1, sensor 1)",
  P0135: "O2 sensor heater circuit (bank 1, sensor 1)",
  P0136: "O2 sensor circuit (bank 1, sensor 2)",
  P0137: "O2 sensor circuit low voltage (bank 1, sensor 2)",
  P0138: "O2 sensor circuit high voltage (bank 1, sensor 2)",
  P0139: "O2 sensor circuit slow response (bank 1, sensor 2)",
  P0140: "O2 sensor circuit no activity detected (bank 1, sensor 2)",
  P0141: "O2 sensor heater circuit (bank 1, sensor 2)",
  P0171: "System too lean (bank 1)",
  P0172: "System too rich (bank 1)",
  P0174: "System too lean (bank 2)",
  P0175: "System too rich (bank 2)",
  P0190: "Fuel rail pressure sensor circuit",
  P0191: "Fuel rail pressure sensor circuit range/performance",
  // --- Injector circuits ---
  P0201: "Injector circuit, cylinder 1",
  P0202: "Injector circuit, cylinder 2",
  P0203: "Injector circuit, cylinder 3",
  P0204: "Injector circuit, cylinder 4",
  P0217: "Engine over-temperature condition",
  P0219: "Engine overspeed condition",
  P0234: "Turbocharger/supercharger overboost condition",
  P0299: "Turbocharger/supercharger underboost condition",
  // --- Ignition and misfire ---
  P0300: "Random/multiple cylinder misfire detected",
  P0301: "Cylinder 1 misfire detected",
  P0302: "Cylinder 2 misfire detected",
  P0303: "Cylinder 3 misfire detected",
  P0304: "Cylinder 4 misfire detected",
  P0305: "Cylinder 5 misfire detected",
  P0306: "Cylinder 6 misfire detected",
  P0315: "Crankshaft position system variation not learned",
  P0325: "Knock sensor 1 circuit",
  P0335: "Crankshaft position sensor A circuit",
  P0336: "Crankshaft position sensor A circuit range/performance",
  P0340: "Camshaft position sensor A circuit",
  P0341: "Camshaft position sensor A circuit range/performance",
  // --- Emission controls ---
  P0401: "Exhaust gas recirculation flow insufficient detected",
  P0402: "Exhaust gas recirculation flow excessive detected",
  P0403: "Exhaust gas recirculation control circuit",
  P0420: "Catalyst system efficiency below threshold (bank 1)",
  P0430: "Catalyst system efficiency below threshold (bank 2)",
  P0441: "Evaporative emission system incorrect purge flow",
  P0442: "Evaporative emission system leak detected (small leak)",
  P0455: "Evaporative emission system leak detected (gross leak)",
  P0456: "Evaporative emission system leak detected (very small leak)",
  P0480: "Cooling fan 1 control circuit",
  // --- Speed, idle and inputs ---
  P0500: "Vehicle speed sensor A",
  P0505: "Idle air control system",
  P0506: "Idle air control system RPM lower than expected",
  P0507: "Idle air control system RPM higher than expected",
  P0521: "Engine oil pressure sensor/switch range/performance",
  P0562: "System voltage low",
  P0563: "System voltage high",
  // --- Computer output and modules ---
  P0600: "Serial communication link",
  P0603: "Internal control module keep alive memory error",
  P0606: "ECM/PCM processor fault",
  P062F: "Internal control module EEPROM error",
  // --- Transmission ---
  P0700: "Transmission control system (malfunction indicator request)",
  P0705: "Transmission range sensor circuit (PRNDL input)",
  P0715: "Input/turbine speed sensor circuit",
  P0720: "Output speed sensor circuit",
  P0730: "Incorrect gear ratio",
  P0741: "Torque converter clutch circuit performance or stuck off",
  P0744: "Torque converter clutch circuit intermittent",
  // --- Diesel particulate and NOx ---
  P2002: "Diesel particulate filter efficiency below threshold (bank 1)",
  P2003: "Diesel particulate filter efficiency below threshold (bank 2)",
  P2452: "Diesel particulate filter pressure sensor A circuit",
  P2453: "Diesel particulate filter pressure sensor A circuit range/performance",
  P242F: "Diesel particulate filter restriction: ash accumulation",
  P2463: "Diesel particulate filter restriction: soot accumulation",
  P20EE: "SCR NOx catalyst efficiency below threshold (bank 1)",
  P2279: "Intake air system leak",
  P2096: "Post catalyst fuel trim system too lean (bank 1)",
  P2097: "Post catalyst fuel trim system too rich (bank 1)",
  P2187: "System too lean at idle (bank 1)",
  P2188: "System too rich at idle (bank 1)",
  P2195: "O2 sensor signal biased/stuck lean (bank 1, sensor 1)",
  P2196: "O2 sensor signal biased/stuck rich (bank 1, sensor 1)",
  // --- Chassis: ABS, brakes, steering ---
  C0035: "Left front wheel speed sensor circuit",
  C0040: "Right front wheel speed sensor circuit",
  C0045: "Left rear wheel speed sensor circuit",
  C0050: "Right rear wheel speed sensor circuit",
  C0051: "Steering wheel position sensor circuit",
  C0110: "Pump motor circuit",
  C0121: "Valve relay circuit",
  C0161: "ABS/TCS brake switch circuit",
  C0265: "Electronic brake control module relay circuit",
  // --- Body: airbags and restraints ---
  B0001: "Driver frontal stage 1 deployment control",
  B0010: "Passenger frontal stage 1 deployment control",
  B0020: "Left side airbag deployment control",
  B0028: "Right side airbag deployment control",
  B0051: "Driver seat belt pretensioner deployment control",
  B0052: "Passenger seat belt pretensioner deployment control",
  B0081: "Driver seat position sensor",
  B1000: "Electronic control unit fault",
  // --- Network ---
  U0001: "High speed CAN communication bus",
  U0100: "Lost communication with ECM/PCM A",
  U0101: "Lost communication with transmission control module",
  U0121: "Lost communication with anti-lock brake system control module",
  U0140: "Lost communication with body control module",
  U0155: "Lost communication with instrument panel cluster control module",
  U0401: "Invalid data received from ECM/PCM A",
  U0121_ALT: "Lost communication with ABS control module",
};

/** Codes whose underlying fault is a RED-tier job, so the app must refer out. */
export const RED_CODE_PREFIXES = ["B00", "B005", "B008"];
